# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deepsource < Formula
  desc "Command line interface to DeepSource"
  homepage "https://github.com/deepsourcelabs/cli"
  version "0.3.4"
  license "BSD 2-Clause Simplified License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/deepsourcelabs/cli/releases/download/v0.3.4/deepsource_0.3.4_darwin_arm64.tar.gz"
      sha256 "3b2a802138947545768ccbd7226ff0e38e27e15d31b3616b6c2e2d03dd4a7fa9"

      def install
        bin.install "deepsource"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/deepsourcelabs/cli/releases/download/v0.3.4/deepsource_0.3.4_darwin_x86_64.tar.gz"
      sha256 "0737b2967408d62dc31906a231fa911bbc2438acab3e94980fd1bcdbc8a95f75"

      def install
        bin.install "deepsource"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepsourcelabs/cli/releases/download/v0.3.4/deepsource_0.3.4_linux_arm64.tar.gz"
      sha256 "1b7a09b0a89e90639f3bdf99e565c383cef003f6fa89eff164ba9e4615c9153c"

      def install
        bin.install "deepsource"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/deepsourcelabs/cli/releases/download/v0.3.4/deepsource_0.3.4_linux_x86_64.tar.gz"
      sha256 "cfc5afc29c1bd4f20817de7fd81d629132000e039d6d4edc60ba751cbf6589f0"

      def install
        bin.install "deepsource"
      end
    end
  end
end
