# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deepsource < Formula
  desc "Command line interface to DeepSource"
  homepage "https://github.com/deepsourcelabs/cli"
  version "0.8.5"
  license "BSD 2-Clause Simplified License"

  on_macos do
    url "https://github.com/DeepSourceCorp/cli/releases/download/v0.8.5/deepsource_0.8.5_darwin_x86_64.tar.gz"
    sha256 "0608f80dcef6f02977d1d667d3910184ed1680e53d4c78bc6f6a90fcaf54eb48"

    def install
      bin.install "deepsource"
      bash_completion.install "completions/deepsource.bash" => "deepsource"
      zsh_completion.install "completions/deepsource.zsh" => "_deepsource"
      fish_completion.install "completions/deepsource.fish"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Deepsource
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/DeepSourceCorp/cli/releases/download/v0.8.5/deepsource_0.8.5_linux_x86_64.tar.gz"
      sha256 "75ce608e70282165d8058c8e59f07a83ce803f43091565b01041151034d09fd3"

      def install
        bin.install "deepsource"
        bash_completion.install "completions/deepsource.bash" => "deepsource"
        zsh_completion.install "completions/deepsource.zsh" => "_deepsource"
        fish_completion.install "completions/deepsource.fish"
      end
    end
  end
end
