# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deepsource < Formula
  desc "Command line interface to DeepSource"
  homepage "https://github.com/deepsourcelabs/cli"
  version "0.3.6"
  license "BSD 2-Clause Simplified License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deepsourcelabs/cli/releases/download/v0.3.6/deepsource_0.3.6_darwin_x86_64.tar.gz"
      sha256 "4d05d21d19f5ac61b71dd80765b1756c20dd0e94a3dbeb046db8d15945ef1b58"

      def install
        bin.install "deepsource"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deepsourcelabs/cli/releases/download/v0.3.6/deepsource_0.3.6_darwin_arm64.tar.gz"
      sha256 "cae5941fc3daaff21883353f05800acffc1e9ddb4431ac518f688ae13c13f8dd"

      def install
        bin.install "deepsource"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepsourcelabs/cli/releases/download/v0.3.6/deepsource_0.3.6_linux_arm64.tar.gz"
      sha256 "b16b6e8c6a665e568c547d27196d7883f273e0b1083df915a84c228835abd2b8"

      def install
        bin.install "deepsource"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/deepsourcelabs/cli/releases/download/v0.3.6/deepsource_0.3.6_linux_x86_64.tar.gz"
      sha256 "72d1993e06d17d20bf12822040e9ed4e6b57c11a0ad46f34fc146a14edfce114"

      def install
        bin.install "deepsource"
      end
    end
  end
end
